server:
  port: 8090
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
  
spring:  
  datasource:
    url : jdbc:mysql://localhost:3306/racing?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8 
    username : root
    password : LiXd1997.
    driverClassName : com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hiccup.domain
    